# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYTimesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYTimesApp
  pod 'Alamofire'

  target 'NYTimesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTimesAppUITests' do
    # Pods for testing
  end

end
